### ISSUE TITLE
K8s client JSON error

### ISSUE THREAD

**Issue by benbromhead** [instaclustr/cassandra-operator#144]
Turns out we are hitting this https://github.com/kubernetes-client/java/issues/86

ERROR [OperatorService] c.g.c.util.concurrent.ServiceManager: Service OperatorService [FAILED] has failed in the RUNNING state.
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 4211 path $.status
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at io.kubernetes.client.JSON.deserialize(JSON.java:108)
	at io.kubernetes.client.ApiClient.deserialize(ApiClient.java:668)
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:871)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.AppsV1beta2Api.deleteNamespacedStatefulSetWithHttpInfo(AppsV1beta2Api.java:2581)
	at io.kubernetes.client.apis.AppsV1beta2Api.deleteNamespacedStatefulSet(AppsV1beta2Api.java:2560)
	at com.instaclustr.cassandra.operator.k8s.K8sResourceUtils.deleteStatefulSet(K8sResourceUtils.java:126)
	at com.instaclustr.cassandra.operator.controller.DataCenterDeletionController.deleteDataCenter(DataCenterDeletionController.java:45)
	at com.instaclustr.cassandra.operator.service.OperatorService.run(OperatorService.java:111)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 4211 path $.status
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:418)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:406)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	... 15 common frames omitted

**Comment by benbromhead** [comment]
Work around is to catch exception and move on (or retry until status is returned)

**Comment by benbromhead** [comment]
#143
