### ISSUE TITLE
First Cassandra pod sometimes restarts twice during bootstrap

### ISSUE THREAD

**Issue by johananl** [instaclustr/cassandra-operator#296]
Looks like the first Cassandra pod in a cluster always restarts twice during bootstrap. Inspection of the logs shows the following:

```
WARN  [main] SeedProvider.java:33 Unable to resolve k8s service cassandra-test-dc-cassandra-seeds.
java.net.UnknownHostException: cassandra-test-dc-cassandra-seeds: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_222]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[na:1.8.0_222]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[na:1.8.0_222]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277) ~[na:1.8.0_222]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[na:1.8.0_222]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[na:1.8.0_222]
	at com.instaclustr.cassandra.k8s.SeedProvider.getSeeds(SeedProvider.java:26) ~[cassandra-k8s-addons-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
	at org.apache.cassandra.config.DatabaseDescriptor.applySeedProvider(DatabaseDescriptor.java:903) [apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.config.DatabaseDescriptor.applyAll(DatabaseDescriptor.java:330) [apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:148) [apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:132) [apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.service.CassandraDaemon.applyConfig(CassandraDaemon.java:665) [apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:609) [apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:732) [apache-cassandra-3.11.4.jar:3.11.4]
Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: The seed provider lists no seeds.
The seed provider lists no seeds.
ERROR [main] CassandraDaemon.java:749 Exception encountered during startup: The seed provider lists no seeds.
```

This is most likely caused by the fact that Cassandra nodes try to form a cluster using the `cassandra-test-dc-cassandra-seeds` service, which doesn't have any active endpoints before the first node had joined the cluster.

While this doesn't cause a real problem due to k8s' automatic convergence, this does make the user experience a bit worse in my opinion since we always have restarts on one of the Cassandra pods:

```
kubectl get pods
```

```
NAME                                  READY   STATUS    RESTARTS   AGE
cassandra-operator-54464bcf4-nb6t2    1/1     Running   0          11m
cassandra-test-dc-cassandra-rack1-0   2/2     Running   2          9m28s
cassandra-test-dc-cassandra-rack1-1   2/2     Running   0          7m48s
cassandra-test-dc-cassandra-rack1-2   2/2     Running   0          6m10s
```

This can most likely be resolved with the help of an init container which waits for a desired condition rather than failing immediately when the service isn't in the desired state.

**Comment by johananl** [comment]
Looks like this only occurs on the **first** time a Cassandra cluster is created on a given k8s cluster. When deleting the Cassandra cluster and re-creating it the pod doesn't restart anymore.

**Comment by smiklosovic** [comment]
The most probable reason this was happening was that in Sidecar, when that container starts, it was doing some JMX calls to Cassandra but Cassandra was not there yet, so that  container has failed to start (this call was done as part of that process initialisation). In the upcoming release, I have refactored the code in a such way that this is not called prematurely so container will not fail, hence no restarts will be done.
