### ISSUE TITLE
fix nodetool in 4.x Cassandra

### ISSUE THREAD

**Issue by smiklosovic** [instaclustr/cassandra-operator#345]
```
ERROR [main] FileUtils.java:93 FATAL: Cassandra is unable to access required classes. This usually means it has been run without the aid of the standard startup scripts or the scripts have been edited. If this was intentional, and you are attempting to use Java 11+ you may need to add the --add-exports and --add-opens jvm options from either jvm11-server.options or jvm11-client.options
error: access to public member failed: jdk.internal.ref.Cleaner.clean[Ljava.lang.Object;@93081b6/invokeVirtual, from org.apache.cassandra.io.util.FileUtils (unnamed module @6b8ca3c8)
-- StackTrace --
java.lang.IllegalAccessException: access to public member failed: jdk.internal.ref.Cleaner.clean[Ljava.lang.Object;@93081b6/invokeVirtual, from org.apache.cassandra.io.util.FileUtils (unnamed module @6b8ca3c8)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:942)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:2206)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkMethod(MethodHandles.java:2146)
```

**Comment by smiklosovic** [comment]
This was fixed as part of https://github.com/instaclustr/cassandra-operator/pull/359
