### ISSUE TITLE
[BUG] Cluster fails with error 

### ISSUE THREAD

**Issue by deep1pradee** [instaclustr/cassandra-operator#389]
I have tried to start the cluster with example-datacenter.yaml
the POD create a PVC and fails with below error 
````
ERROR [main] CassandraDaemon.java:774 Exception encountered during startup
java.lang.IllegalStateException: Unable to resolve any seeds!
	at com.instaclustr.cassandra.k8s.SeedProvider.getSeeds(SeedProvider.java:27) ~[cassandra-3-k8s-addons-1.0.2.jar:na]
	at org.apache.cassandra.config.DatabaseDescriptor.applySeedProvider(DatabaseDescriptor.java:941) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.config.DatabaseDescriptor.applyAll(DatabaseDescriptor.java:338) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:153) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:137) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.CassandraDaemon.applyConfig(CassandraDaemon.java:675) [apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:619) [apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:757) [apache-cassandra-3.11.6.jar:3.11.6]
Caused by: java.lang.IllegalStateException: Seed list is empty!
	at com.instaclustr.cassandra.k8s.SeedsResolver.resolve(SeedsResolver.java:63) ~[cassandra-k8s-addons-1.0.1.jar:na]
	at com.instaclustr.cassandra.k8s.SeedProvider.getSeeds(SeedProvider.java:25) ~[cassandra-3-k8s-addons-1.0.2.jar:na]
	... 7 common frames omitted
`````

Currently im using the Ceph block to create the PVC

The other nodes are not coming up... Its failing with the first pod itself.

I have not changed anything on the yaml file..
I have specified only the storage class to my ceph.

spec from example-datacenter.yaml
```
spec:
  prometheusSupport: false
  optimizeKernelParams: true
  serviceAccountName: cassandra-performance
  nodes: 3
  cassandraImage: "gcr.io/cassandra-operator/cassandra-3.11.6:latest"
  sidecarImage: "gcr.io/cassandra-operator/cassandra-sidecar:latest"
  imagePullPolicy: Always

  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi
  sidecarResources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    storageClassName: rook-ceph-block
    resources:
      requests:
        storage: 2Gi
```

kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by smiklosovic** [comment]
@deep1pradee please copy here the content of /etc/resolv.conf of that container.

**Comment by deep1pradee** [comment]
@smiklosovic  Since the container is failing, I can't go inside the container.

**Comment by smiklosovic** [comment]
@deep1pradee it should be in logs of Cassandra as it starts, (kubectl logs -f _that container_) 

Look for `Content of /etc/resolv.conf` in it, it is logged.

I suppose it is same as in Sidecar though.

It does nothing else but this

https://github.com/instaclustr/cassandra-operator/blob/master/java/cassandra-k8s-addons/src/main/java/com/instaclustr/cassandra/k8s/SeedsResolver.java#L120-L153

So it will take `test-c1.svc.kubet-cluster.internal` and prepends name of service to it and then it uses `dig` 

https://github.com/instaclustr/cassandra-operator/blob/master/java/cassandra-k8s-addons/src/main/java/com/instaclustr/cassandra/k8s/SeedsResolver.java#L72

Try to go to sidecar and execute

`dig -t SRV {something.test-c1.svc.kubet-cluster.internal} +short`

replace "something" with name of service.

**Comment by deep1pradee** [comment]
@smiklosovic it could be DNS resolution is not working? how to resolve this issue?

**Comment by smiklosovic** [comment]
Your `/etc/resolv.conf` seems fine. If you followed my suggestions, what does `dig` return? Nothing?

**Comment by deep1pradee** [comment]
@smiklosovic It was an issue with our local DNS setup of K8s.. Since we using our custom dns in the setup the seed was not able to resolving.. Its fixed now...
