### ISSUE TITLE
Warning "Unprocessable Entity"

### ISSUE THREAD

**Issue by liwang-pivotal** [instaclustr/cassandra-operator#41]
When a scale down command is triggered, got the warning as below:
```
16:14:15.727 [ControllerService] WARN  c.i.c.operator.k8s.K8sResourceUtils - Failed to update resource. This will be a hard exception in the future.
io.kubernetes.client.ApiException: Unprocessable Entity
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:781)
	at com.instaclustr.cassandra.operator.k8s.K8sResourceUtils.lambda$createOrReplaceResource$1(K8sResourceUtils.java:51)
	at com.instaclustr.cassandra.operator.k8s.K8sResourceUtils.createOrReplaceResource(K8sResourceUtils.java:41)
	at com.instaclustr.cassandra.operator.k8s.K8sResourceUtils.createOrReplaceResource(K8sResourceUtils.java:49)
	at com.instaclustr.cassandra.operator.k8s.K8sResourceUtils.createOrReplaceNamespaceService(K8sResourceUtils.java:60)
	at com.instaclustr.cassandra.operator.service.ControllerService.createOrReplaceNodesService(ControllerService.java:279)
	at com.instaclustr.cassandra.operator.service.ControllerService.createOrReplaceDataCenter(ControllerService.java:128)
	at com.instaclustr.cassandra.operator.service.ControllerService.run(ControllerService.java:119)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by benbromhead** [comment]
+1 seen this as well

**Comment by liwang-pivotal** [comment]
I'm testing and seeing this also when scaling. Looks like replace `service` resource will cause this exception, `configmap` and `statefulset` will work as normal.

**Comment by liwang-pivotal** [comment]
PR #48
