### ISSUE TITLE
Operator Restarted Once when Creating DC

### ISSUE THREAD

**Issue by liwang-pivotal** [instaclustr/cassandra-operator#44]
```
18:14:33.431 [CassandraHealthCheckService RUNNING] ERROR c.g.c.util.concurrent.ServiceManager - Service CassandraHealthCheckService [FAILED] has failed in the RUNNING state.
java.lang.NullPointerException: null
	at com.google.common.net.InetAddresses.ipStringToBytes(InetAddresses.java:162)
	at com.google.common.net.InetAddresses.forString(InetAddresses.java:136)
	at com.instaclustr.cassandra.operator.service.CassandraHealthCheckService.runOneIteration(CassandraHealthCheckService.java:63)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:193)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zegelin** [comment]
I've seen this too. Will investigate.

**Comment by benbromhead** [comment]
Closing due to merged fixes, no operator restarts seen in testing atm
