### ISSUE TITLE
Null Pointer Exception prevents cluster creation

### ISSUE THREAD

**Issue by snoopdave** [instaclustr/cassandra-operator#95]
I installed via Helm, and saw that the operator was up and running:

```
k get pods
NAME                                  READY     STATUS    RESTARTS   AGE
cassandra-operator-549744c8fc-w6p47   1/1       Running   0          44m
```

But then when I create a cluster, also via Helm, the Cassandra pods are not created and I see this in the operator's logs:

```
java.lang.NullPointerException: null
	at com.instaclustr.cassandra.operator.controller.DataCenterReconciliationController.createOrReplaceNodesService(DataCenterReconciliationController.java:417)
	at com.instaclustr.cassandra.operator.controller.DataCenterReconciliationController.reconcileDataCenter(DataCenterReconciliationController.java:66)
	at com.instaclustr.cassandra.operator.service.OperatorService.run(OperatorService.java:106)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.lang.Thread.run(Thread.java:748)
```

Any ideas what I might have done wrong?

**Comment by benbromhead** [comment]
Hi @snoopdave 

Thanks for the feedback. It looks like we missed updating the helm package to include the Prometheus support flag. 

I've created the PR #96 to fix it and I will merge shortly.

Ben

**Comment by benbromhead** [comment]
Just merged, you should no longer get the NPE when creating a cluster via the helm package. 

Feel free to reopen/comment if you are still getting this issue.

**Comment by snoopdave** [comment]
Thanks! that worked for me.
